webtalk_init -webtalk_dir D:/Projects/SOC_Projects/SPI_SLAVE_CORE/SPI_SLAVE_CORE.sim/sim_1/behav/xsim/xsim.dir/TB_SPI_SLAVE_CORE_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Feb 24 03:56:05 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d880e6f4-7ac6-4d1a-bf0d-091f4aaee1c8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "15b83e86a51f40579740af4be7242472" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "62" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7820HK CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.14_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "10232_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1225263129 -regid "" -xml D:/Projects/SOC_Projects/SPI_SLAVE_CORE/SPI_SLAVE_CORE.sim/sim_1/behav/xsim/xsim.dir/TB_SPI_SLAVE_CORE_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Projects/SOC_Projects/SPI_SLAVE_CORE/SPI_SLAVE_CORE.sim/sim_1/behav/xsim/xsim.dir/TB_SPI_SLAVE_CORE_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Projects/SOC_Projects/SPI_SLAVE_CORE/SPI_SLAVE_CORE.sim/sim_1/behav/xsim/xsim.dir/TB_SPI_SLAVE_CORE_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
